version: '3.8'
services:
  postgres:
    container_name: postgres-stardew-accounting
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB_NAME: postgres
    ports:
      - "5432:5432"
